### ISSUE TITLE
Detect Group Type in WP Nav Menu so that "Group Type Page" is highlighted

### ISSUE THREAD

**Issue by BoweFrankema** [CFCommunity-net/buddypress-group-types#11]
Currently if you view a single Group Type page it will always think you're on a regular Group page and in your WordPress Menu the "Groups" page is "active".

**Comment by slaFFik** [comment]
Will push this code today.

**Comment by BoweFrankema** [comment]
Awesome!

**Comment by BoweFrankema** [comment]
For some reason this does not seem to work for me. Could it be because I'm using a custom walker? https://github.com/CFCommunity-net/cfcommunity/blob/master/wp-content/themes/cfcommunity/lib/menus.php#L128

**Comment by slaFFik** [comment]
In your code change this line: 
`add_filter('nav_menu_css_class', 'cfc_nav_menu_css_class', 10, 2);`
to this one
`add_filter('nav_menu_css_class', 'cfc_nav_menu_css_class', 100, 2);`
Note the change priority. I believe that should fix the issue.

**Comment by slaFFik** [comment]
In my code I applied 90 to make the room for other plugins to change what they need, and on 10 I just don't have required data. Your code depends on changes of mine code, so that should be a quick and easy fix.

**Comment by BoweFrankema** [comment]
That fixed the issue! Thanks again Slava.. Really happy to see this work!
