### ISSUE TITLE
Custom Group Meta for Group Types

### ISSUE THREAD

**Issue by BoweFrankema** [CFCommunity-net/buddypress-group-types#13]
The last feature we would need to add to get the group types complete is adding a way to manage Group Meta per group type. 

This would allow us to display relevant data in the group header and group type directories. Goals

1 - Admin can add/edit group meta per group type
2 - Group meta is asked on group creation
3 - Provide option to skip certain group meta fields on group creation (not required fields)

That's it!

**Comment by slaFFik** [comment]
Not sure I understand the purpose...
Are you talking about the same or similar UI we have on post create page in wp-admin with custom fields? Like defining the key and save a value for it. Or are you talking about smth different?

**Comment by BoweFrankema** [comment]
The functionality and UI/UX I have described here. I think our idea was to make it a seperate plugin (premium extension) to control group fields per group type. Here are the screenshots I made

https://trello.com/c/lThQ47uv/15-buddypress-group-fields

**Comment by slaFFik** [comment]
ah, you are talking about THAT fields! :)
Gotcha. Definitely a separate plugin.
This should be a separate repo (private) for a plugin. I guess this issue can be removed after that.

**Comment by slaFFik** [comment]
Closing this issue as we have a separate repo for that functionality.
