### ISSUE TITLE
Next: Enable / Disable Group Extensions/plugins

### ISSUE THREAD

**Issue by BoweFrankema** [CFCommunity-net/buddypress-group-types#9]
Add the ability to enable or disable Group plugins/extensions per Group Type. Notes from Boone:

"for group extensions, there is currently no easy way to do it on a per-group basis, but you can hook in early to the screen loading process for groups (+ group admin, + group creation, + groups dashboard panel) and just remove the irrelevant items from the nav global".

See the attached mock-up for an UI example

![screenshot 2014-12-16 11 47 59](https://cloud.githubusercontent.com/assets/855037/5452286/6c68568c-8519-11e4-98c1-d739149f35a3.png)

**Comment by BoweFrankema** [comment]
Hi Slava,

Any updates on this?

**Comment by slaFFik** [comment]
Currently working on a prototype, not yet ready for release.
